### ISSUE TITLE
An error importing in TypeScript under Nest

### ISSUE THREAD

**Issue by ghost** [Flagsmith/flagsmith-nodejs-client#105]
Hi,
I'm having the following error when importing the package to initialize the first connection.

> TypeError: flagsmith_nodejs_1.default is not a constructor

Typescript compiles 
`new Flagsmith({})`
to:
`const flagsmith = new flagsmith_nodejs_1.default({})`

Thanks a lot for your consideration

**Comment by kyle-ssg** [comment]
Hi @bacloud23, could I ask if you're using the latest version of ``flagsmith-nodejs`` and how you're attempting to import?

Given the following in ``Node v16.15.1`` I am able to use the SDK:


```
import Flagsmith from 'flagsmith-nodejs'
const environmentKey = 'NowEDzKzNJXZVTVanLVdMQ';
const flagsmith = new Flagsmith({
    environmentKey
});
```

**Comment by bacloud23** [comment]
I note that I'm using it with Nest which does use TypeScript compiler (somehow/ I really don't know)

```
Node: v14.19.0
Nestjs/cli: 7.5.6
```

Thanks for your consideration

**Comment by kyle-ssg** [comment]
No problem! I'll see if I can get a Nest example added to the repo / replicate the issue.

**Comment by bacloud23** [comment]
Hi @kyle-ssg 
This is a reproduction: https://github.com/bacloud23/flagsmith-nodejs-client-issue

**Comment by kyle-ssg** [comment]
I can replicate it too however I'm not quite sure why yet.


Given the following

```
import Flagsmith from 'flagsmith-nodejs'
```

Vanilla NodeJS project: working
Nest JS project: Flagsmith is undefined


Whilst I diagnose I can confirm the following works in Nest: 


```
const Flagsmith = require('flagsmith-nodejs')
```

**Comment by kyle-ssg** [comment]
Ok, a bit of progress. Adding the following to your TS config would fix being able to import.

```
"esModuleInterop": true
```

**Comment by bacloud23** [comment]
I will check as soon as I can thanks a lot

**Comment by bacloud23** [comment]
I'm no TS expert, but from https://stackoverflow.com/questions/56238356/understanding-esmoduleinterop-in-tsconfig-file
I guess if you instead export Flagsmith like other Classes and not default (namespace of "flagsmith-nodejs" index), all these would be resolved.

But I guess that would be a breaking change.

**Comment by kyle-ssg** [comment]
Yeah, I think I'd rather break the ability to require("flagsmith-nodejs") vs require("flagsmith-nodejs").default  than do that. 

I wonder if a less extreme solution would be to add export Flagsmith whilst keeping the default exports, then people can just add esModuleInterop or just ``import {Flagsmith}``

**Comment by bacloud23** [comment]
yes both ways should be feasible and doesn't break anything I guess. 
thanks a lot

**Comment by bacloud23** [comment]
I will try to work on this if I can.
Thank you for your support !
