### ISSUE TITLE
[Question] What is the behaviour of `getIdentityFlags`

### ISSUE THREAD

**Issue by bacloud23** [Flagsmith/flagsmith-nodejs-client#109]
Hi,
I could run `getIdentityFlags(email)` and that automatically set the default features for that user. Is this the normal attended behaviour? I didn't insert the user! so there is not `setIdentityFlags` or `initIdentityFlags` etc to add user with default features manually ?

Thanks a lot :)

**Comment by dabeeeenster** [comment]
What do you mean by "I didn't insert the user"? Identities are *lazily created* when they are first encountered.

**Comment by bacloud23** [comment]
That was not really obvious to me. ok now I understand thanks :)

**Comment by dabeeeenster** [comment]
Its the second paragraph here! https://docs.flagsmith.com/basic-features/managing-identities
