### ISSUE TITLE
Export `FlagsmithConfig` from index

### ISSUE THREAD

**Issue by jake-p-swyftx** [Flagsmith/flagsmith-nodejs-client#135]
It would be helpful if `FlagsmithConfig` was exported from the package index here: https://github.com/Flagsmith/flagsmith-nodejs-client/blob/main/index.ts#L3

It's currently possible to obtain a reference to the type a couple of different ways, but they are a bit roundabout:
```
import { FlagsmithConfig } from 'flagsmith-nodejs/build/sdk';
```
or
```
import Flagsmith from 'flagsmith-nodejs';
type FlagsmithConfig = ConstructorParameters<typeof Flagsmith>[0];
```

**Comment by matthewelwell** [comment]
Thanks for this @jake-p-swyftx. We're open to receiving a PR on this if you are keen to do so.
