### ISSUE TITLE
Check if flag is "server-side only"

### ISSUE THREAD

**Issue by dhferreira** [Flagsmith/flagsmith-nodejs-client#144]
Hi,

is there a way to check if some feature is server-side only? I am trying to use this lib in my backend, but here for some business rules I need to know if some flag has the option "server-side only" set.

Thanks.

**Comment by matthewelwell** [comment]
Hi @dhferreira, that's interesting. There isn't any way currently to do that, no. I would recommend perhaps using a naming convention to achieve this?
