### ISSUE TITLE
Specifying an API should include the trailing slash

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith-nodejs-client#19]
https://github.com/Flagsmith/flagsmith-nodejs-client/blob/179a9fa11042fee9946cf14bd875e7012251bc26/flagsmith-core.js#L60 should read 

```
        this.api = api || 'https://api.flagsmith.com/api/v1/';
```

**Comment by yuriihorodnyi21** [comment]
@dabeeeenster , I believe this issue is no longer relevant? (see https://github.com/Flagsmith/flagsmith-nodejs-client/blob/main/sdk/index.ts#L17)
