### ISSUE TITLE
Add better logging when HTTP errors are thrown

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith-nodejs-client#33]
If it were possible to add some error handling on the call to res.json() (https://github.com/Flagsmith/flagsmith-nodejs-client/blob/bd66dcc582e176a5b78fe1d6a1f68706429f62ed/flagsmith-core.js#L46) which returned some more helpful information about the error it would be easier to diagnose errors, from the API, particularly instances of 5XX response codes.

**Comment by yuriihorodnyi21** [comment]
@dabeeeenster  As of the v2 we already have more usable request handling, but I've also added additional logging [here](https://github.com/Flagsmith/flagsmith-nodejs-client/pull/45) if that's what you had in mind?

**Comment by dabeeeenster** [comment]
👍
