### ISSUE TITLE
Build folder is missing

### ISSUE THREAD

**Issue by shrujalshah28** [Flagsmith/flagsmith-nodejs-client#40]
https://registry.npmjs.org/flagsmith-nodejs/-/flagsmith-nodejs-2.0.0.tgz

The build folder is not present in the npm package.

**Comment by kyle-ssg** [comment]
[Fixed in 2.0.2](https://registry.npmjs.org/flagsmith-nodejs/-/flagsmith-nodejs-2.0.2.tgz)

**Comment by shrujalshah28** [comment]
Thank you for quick fix 👍🏼
