### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by fahyik** [Flagsmith/flagsmith-nodejs-client#42]
hi do you plan to introduce typescript support any time soon?

it seems we can't get the library to work with the import syntax

it throws an `TypeError: _flagsmithNodejs.Flagsmith is not a constructor` error

**Comment by kyle-ssg** [comment]
Hey, everything is already fully typed, so I'm not sure what you mean by TypeScript support. As for ES importing I'll take a look.

**Comment by kyle-ssg** [comment]
In the meantime ``const flagsmith = require('flagsmith-nodejs')`` as per our example has full TypeScript support.

**Comment by kyle-ssg** [comment]
Hey, this should be resolved in 2.1.0 - please re-open if there are any issues!
