### ISSUE TITLE
Set User Trait

### ISSUE THREAD

**Issue by huantbui** [Flagsmith/flagsmith-nodejs-client#49]
In flagsmith-nodejs v1, it has function: `setTrait(identity, key, value)` ... this allows to store user's identity.  Now, it's no longer there... can we have it back?

**Comment by matthewelwell** [comment]
Hi @huantbui, you can now achieve this using the `getIdentityFlags` method. 

For example:

```javascript
flagsmith.getIdentityFlags("my-identity", { "trait-key": "trait-value" })
```

I'm going to update the documentation tomorrow to explain this a little better as I agree that it's not clear at the moment that this is possible.

**Comment by huantbui** [comment]
So `getIdentityFlags` will also `set` identity?  I see it now via documentation: https://github.com/Flagsmith/flagsmith-nodejs-client/blob/main/sdk/index.ts#L159-L161

**Comment by matthewelwell** [comment]
That's correct, yes.
