### ISSUE TITLE
`import {Flags} from 'flagsmith-nodejs'` has Flags as undefined

### ISSUE THREAD

**Issue by sakekasi** [Flagsmith/flagsmith-nodejs-client#53]
Here's a sample program:
```
import Flagsmith, {Flags} from 'flagsmith-nodejs';
import * as f from 'flagsmith-nodejs';

console.log('Flagsmith', Flagsmith); // prints a function
console.log('Flags', Flags); // prints 'undefined', even though the types say that this is a class
console.log('f', f); prints {... Flags: undefined, ..., Flagsmith: [Function: Flagsmith] ...}
```

I'm using `flagsmith-nodejs@^2.1.1` (from my yarn lock). Looks like the js is not matching up with the typings.

Please LMK how I can address this issue. Thanks!

**Comment by kyle-ssg** [comment]
Hi @sakekasi, can I ask what you're trying to achieve here? "Flags" is exported as just a type, so logging it will output undefined.

**Comment by kyle-ssg** [comment]
Closing as stale. Please feel free to re-open if you think this is an issue.
