### ISSUE TITLE
Regression between v2.1.1 and v2.2.0

### ISSUE THREAD

**Issue by shrujalshah28** [Flagsmith/flagsmith-nodejs-client#57]
This expression is not constructable.
  Type 'typeof import(".../node_modules/flagsmith-nodejs/build/index")' has no construct signatures.ts(2351)

The same error was there with v2.1.0 and solved in v2.1.1, now with v2.2.0, we have the same error.

v2.1.0
![image](https://user-images.githubusercontent.com/14292916/185750906-1522ece2-931b-4538-a07b-5214e97e237b.png)

v2.1.1
![image](https://user-images.githubusercontent.com/14292916/185750844-4fe3d548-87ab-4704-8a91-9e57e1ae1f6a.png)

v2.2.0
![image](https://user-images.githubusercontent.com/14292916/185750888-57e476cf-b2bb-4822-9717-0648594acdb5.png)

**Comment by kyle-ssg** [comment]
Hi, could you try this with flagsmith-nodejs@2.2.2. Please re-open if you believe this is still an issue.

**Comment by shrujalshah28** [comment]
Working fine. Tested with v2.3.0
